executable              = run_job.sh
arguments               = $(chunk) $(Process)
transfer_input_files    = single_mu_selection.py, $(chunk), x509up
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = out_$(Process).root

output                  = logs/job_$(Process).out
error                   = logs/job_$(Process).err
log                     = logs/job.log

# Requesting a small set of cpus/memory
request_cpus            = 4
request_memory          = 4GB
# How long should the job be run before it is cut off? longlunch = 2hrs
+JobFlavour             = "longlunch"

queue chunk matching files chunks/chunk_*